version: "3.8"

services:
  database:
    image: mysql:migs/mysql-5.7
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER:
      MYSQL_USER_PASSWORD:
    volumes:
        - db-data/var/lib/mysql
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
        - clarusnet
    configs:
        -   source: initaldb
            target: /docker-entrypoint-initdb.d/init/sql

  app-server:
    image: "${ECR_REGISTRY}/${APP_REPO_NAME}:latest"
    deploy:
      mode: global
      update_config:
          parallelism: 2
          delay: 5s
          order: start-first
    ports:
     - "80:80"
    networks: 
      - clarusnet

networks:
  clarusnet:
    driver: overlay
volumes:
    db-data:
configs:
  initaldb:
    file: ./init.sql      
